eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.49.2:30902/eureka

server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://ratingsuser:admin123@ratings-db.cluster-c9q44804g06m.us-east-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: ratings-db
      port: 27017




  application:
    name: RATING-SERVICE
  
#  config:
#    import: configserver:http://localhost:8888/
