eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.49.2:31108/eureka

server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://ratingsuser:admin123@127.0.0.1:27017/
      database: rating_db
      port: 27017




  application:
    name: RATING-SERVICE
  
#  config:
#    import: configserver:http://localhost:8888/
