server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratings_db


  application:
    name: RATING-SERVICE
  
  config:
    import: configserver:http://localhost:8085/ 
